spring:
  application:
    name: prices
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    username: sa
    password:
  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
logging:
    level:
      root: INFO
      org.flywaydb: INFO
      org.springframework.r2dbc: WARN
      io.r2dbc.h2: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

openapi:
  dev-url: http://localhost:8080
