spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_R2DBC_USERNAME:sa}
    password: ${SPRING_R2DBC_PASSWORD:}
  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
    user: ${SPRING_FLYWAY_USER:sa}
    password: ${SPRING_FLYWAY_PASSWORD:}
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    root: INFO
    com.commerce.prices: INFO
    org.springframework: WARN